version: "3.9"

services:

  postgres:
    container_name: netflix_db
    image: postgres:14.2
    environment:
      POSTGRES_DB: netflix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - netflix-postgres:/var/lib/postgresql/data


  netflix:
    container_name: netflix-app
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # entrypoint: ["tail", "-f", "/dev/null"]
    build: ./netflix-api
      # dockerfile: ./Dockerfile.local
    volumes:
      - ./netflix-api:/./netflix-api
      # - ./netflix-api:/netflix-api
    links:
      - postgres
    ports:
      - 3000:3000
    # networks:
    #   - back-tier
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  frontend:
    build: ./netflix-ui
    container_name: netflix-ui
    ports:
      - 3001:3001
    expose:
      - 3001
    # networks:
    #   - front-tier
    #   - back-tier
    volumes:
      - ./netflix-ui:/netflix-ui

  app-migrations:
    container_name: app-migrations
    build:
      # context: .
      # dockerfile: netflix-api/Dockerfile
      context: netflix-api
      dockerfile: ../netflix-api/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/setup-db.sh

volumes:
  netflix-postgres:
  netflix:

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}